version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.0-apache
    hostname: apache
    ports:
    - "8080:80" # normal php port for trafic and functionality
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'vyndue03_msgr'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'user'
      # You can use whatever password you like
      # MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    ports:
      - "8183:80" # phpmyadmin login page
    environment:
      PMA_USER: 'root'
      PMA_PASSWORD: 'root'
      PMA_ARBITRARY: 1